spring:
  application:
    name: movie-fun-app

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointURL: http://192.168.138.156:9000
  accessKey: 3AXB08QRY5RNX6MMFA05
  secretKey: hYJBdLHWSn7tfUCTD2e01krsKxlCeOi9GfUAsUNj
  bucketName: luxoft

security:
  basic:
    enabled: false
