---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: movie-fun-cnc-source

outputs:
- name: package-output

run:
  path: movie-fun-cnc-source/ci/tasks/package.sh

