server.port: 8083

spring:
  application:
    name: play-service

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/plays?useSSL=false
    username: root

logging.level:
  root: DEBUG
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

security:
  basic:
    enabled: false
