server.port: 8086

management:
  security:
    enabled: false

spring:
  application:
    name: album-amqp-service

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false
    username: root

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  endpointURL: http://192.168.138.156:9000
  accessKey: 3AXB08QRY5RNX6MMFA05
  secretKey: hYJBdLHWSn7tfUCTD2e01krsKxlCeOi9GfUAsUNj
  bucketName: luxoft

security:
  basic:
    enabled: false

rabbitmq:
  uri: amqp://guest:guest@localhost
  queue: wellsfargo-rabbit-queue


